### ISSUE TITLE
Synchronization

### ISSUE THREAD

**Issue by bladedcharleco** [cortex-lab/neuropixels#43]
I am setting up everything to start neuropixel recordings, but I still have some doubts regarding the sync of neuropixel recorded data and another signal from a microphone (audio) acquired through a National Instruments DAQ. I understand both systems have independent clocks, and a way to sync them would be to send a digital signal to the two of them and later align the time stamps offline with reference to the digital signal. My questions are:
1)  Who would send the digital signal, the NI-DAQ System, or it is required to use an Arduino for this?
2)  What kind of signal is it recommended to send (squared?)?
3)  I have the microphone connected by a BNC connector to AI 1 in the terminal block, would it be enough to connect the sync digital signal to a PFI port (PFI 1 for instance) to be able to acquire both the sync and audio signals by the NI-DAQ? On the neuropixel side, I know that connecting the sync signal to the SMA connector allows for this acquisition module to get neural and sync signals, but I am not so sure how it works on the NI DAQ side.   
4) Does the digital signal connected to both neuropixel and NI-DAQ modules requires to implement also a digital ground?

Specifications: I am using Chassis PXIe-1071 with the IMEC neuropixel acquisition module and a NI-DAQ PXIe-6341 connected to a terminal block BNC-2110.   

Thank you very much for any feedback on this, and it will be very much appreciated. :)

**Comment by nsteinme** [comment]
Hi, yes, I would send a sync signal into both systems. I'd use a digital
signal - it can be either regular or irregular, for instance you can
generate a signal that goes up and down at various times using an arduino,
or you could generate a clock signal with one of the NI DAQ outputs. You
don't need any special grounding situation, I think they are going to share
a ground anyway by going into the same PXI. Basically you just want to set
it up and test whether you can see the same sync timing pulses in both
output data files. If you can, you're set!

**Comment by bladedcharleco** [comment]
Thank you very much, this was very helpful to further clarify ideas!! I will be testing it soon.
