### ISSUE TITLE
how many times can one use a probe for acute recordigs?

### ISSUE THREAD

**Issue by javierzsm** [cortex-lab/neuropixels#46]
Hi, 
I'm trying to estimate how expensive experiments can get doing acute recordings. My question is essentially: how many times can one use a probe to make acute recordings? Which are the critical factors to take into account (besides the handling of the probe, of course)?
I'd appreciate if you could share your experiences. Thank you in advance.
Javier

**Comment by nsteinme** [comment]
There's a supplemental figure in Jun2017 showing that recording quality does not degrade over repeated uses, up to at least 10 uses. Anecdotally, beyond 20 or 25 recordings you may start to see some degradation. In general, you will probably break a probe before you choose to stop using it on account of recording quality.

**Comment by javierzsm** [comment]
Excellent, I guessed it was possible to go beyond 10 recordings because the fig you mention doesn't show degradation at all.
Thanks a lot.
