### ISSUE TITLE
Probe sharpening_re-purposed hard drive method

### ISSUE THREAD

**Issue by aeazraoui** [cortex-lab/neuropixels#49]
Hello everyone,

Did someone manage to find the protocol for the re-purposed hard drive method for probe sharpening?

Thank you in advance.
Best,
Anass

**Comment by nsteinme** [comment]
You should be able to update the wiki!

**Comment by guidomeijer** [comment]
That would be great! But are you sure it's on? I don't see any "edit" button anywhere.

**Comment by nsteinme** [comment]
ok true. I updated it
