### ISSUE TITLE
M9005A PXIe Chassis - IMEC neuropixel card status light is always red.

### ISSUE THREAD

**Issue by Michael-Perkinson** [cortex-lab/neuropixels#52]
Just started using neuropixel 1.0 this week. Fresh install.
In the NI MAX software I can see the chassis but not the IMEC card in slot 2. 
Also the IMEC card does not become listed as a "PCIe Memory Controller" in the device manager and therefore I cannot install Enclustra drivers. 
I am not sure what to do. Any help is appreciated. I can also provide more information if necessary.

We are using:
M9005A PXIe Chassis: 5-slot, 3U, with Integrated System Module
M9005A-002- PCIe Desktop Adapter for M9005A

**Comment by andparra** [comment]
Did you end up figuring out the problem?

**Comment by pascalvogel** [comment]
We have the same issue. Did you solve it?

**Comment by Michael-Perkinson** [comment]
Hi Pascal, 
We did find an easy fix for this issue. The problem was that the firmware on the IMEC stations we received was not compatible with the M9005A Chassis. The simplest solution is to contact someone who regularly works with Neuropixels and ask to swap an IMEC station with them. I recommend reaching out to regular users on the Slack channel for this. If you choose to go this route, make sure never to update the BS and BSC firmware. Doing so could revert the system to a firmware version that is again incompatible with the chassis. Another option is to directly contact IMEC and inquire about a swap.
I hope this is helpful and good luck.
Michael

**Comment by pascalvogel** [comment]
Hi Michael, 
thanks a lot for your quick response! Yes, it seems to be a firmware problem: 
PXIe acquisition module with old firmware (not compatible with X1 slots) + new chassis (PXIe-1083) with X1 slots. 

Solution: 
1) Borrow a chassis with X4 slot 
2) insert acquisition module 
3) update firmware

See also:
http://billkarsh.github.io/SpikeGLX/firmware/
